Metrics/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/HashSyntax:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes

Style/UnlessElse:
  Enabled: false
